#! /bin/sh

# generate the native src
cd test
./bin/create/ios
./bin/create/android
cd ..

# copy plugin into proj
cp -r ./native/ios/* ./tmp/ios/Plugins
cp -r ./native/android/* ./tmp/android

# copy js into proj
cp ./lib/pg-plugin-fb-connect.js ./test/www/pg-plugin-fb-connect.js

# ...and compile
cd test
./bin/debug/ios
./bin/debug/android